apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-walg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-walg@sha256:72bfe105c4328e7e7e18c035d321d5358f6a06317bc82f53686700ea0aaa373f
        name: my-nodejs
        resources: {}
status: {}
